### PR TITLE
task/335-recolor-the-delete-account-dialog

### PR DESCRIPTION
**Pull request by ciripel**

### CODE REVIEW

**Review by tenhobi — COMMENTED** [review]
Changes look OK, yet I think at least the X icon should not have green gradient? Possibly also the "delete" and "loose" words.

now:
image

suggestion:
something like this so it looks "more seriours/scary"?
image

Also I would switch the buttons styles, meaning the "do nothing" should be with the gradient (as primary button) and the "remove" should be only with border (as secondary button).

**Comment by ciripel** [comment]
Even more red?

**Comment by ciripel** [comment]
> Even more red?

Will do!

**Comment by ciripel** [comment]
> Changes look OK, yet I think at least the X icon should not have green gradient? Possibly also the "delete" and "loose" words.
> 
> now: image
> 
> suggestion: something like this so it looks "more seriours/scary"? image
> 
> Also I would switch the buttons styles, meaning the "do nothing" should be with the gradient (as primary button) and the "remove" should be only with border (as secondary button).

done in https://github.com/SimplioOfficial/simplio-app/pull/564/commits/ac59384d812f1456072306a7a5e0230f31542001

**Comment by tenhobi** [comment]
How do you feel about the note I added to the original comment?

> Also I would switch the buttons styles, meaning the "do nothing" should be with the gradient (as primary button) and the "remove" should be only with border (as secondary button).

My point is that we want people to click on "Do nothing", so we should make that a green primary button. And make "remove" red secondary button.

**Comment by ciripel** [comment]
> How do you feel about the note I added to the original comment?
> 
> > Also I would switch the buttons styles, meaning the "do nothing" should be with the gradient (as primary button) and the "remove" should be only with border (as secondary button).
> 
> My point is that we want people to click on "Do nothing", so we should make that a green primary button. And make "remove" red secondary button.

I do not know man... we want to scare them or to get their attention?... i do not think green mixed with red is ok... no idea! let it like this atm and we will see what PO will say

**Comment by ciripel** [comment]
> > How do you feel about the note I added to the original comment?
> > > Also I would switch the buttons styles, meaning the "do nothing" should be with the gradient (as primary button) and the "remove" should be only with border (as secondary button).
> > 
> > 
> > My point is that we want people to click on "Do nothing", so we should make that a green primary button. And make "remove" red secondary button.
> 
> I do not know man... we want to scare them or to get their attention?... i do not think green mixed with red is ok... no idea! let it like this atm and we will see what PO will say
I will present your idea to them also and they can choose

**Comment by tenhobi** [comment]
> I do not know man... we want to scare them or to get their attention?... i do not think green mixed with red is ok... no idea! let it like this atm and we will see what PO will say

I see, ok. Just for the record, this is something like what I meant.

image

**Comment by ciripel** [comment]
> > I do not know man... we want to scare them or to get their attention?... i do not think green mixed with red is ok... no idea! let it like this atm and we will see what PO will say
> 
> I see, ok. Just for the record, this is something like what I meant.
> 
> image

Very good... we have there 2 options they can choose from

**Pull request merged**
